
spring:
  application:
    name: "ENVIOS"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-winter-hill-ap7ofh1t-pooler.c-7.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_vbT2cWqDYPG1

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyenviostodopais@gmail.com
    password: coiegftjqbwmzcqf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


logging:
  level:

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
